spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ttvettlingen24
    username:
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
application:
  import:
    saturday: ${SATURDAY_URL}
    sunday: ${SUNDAY_URL}

